2019-07-22 21:29:27 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=20 from 2019-07-22 12:56:45.011965)
2019-07-22 21:29:28 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: two or more values in the same group of exclusion 'service name' @ data['action'][0][<service name>]. Got None. (See /config/automations.yaml, line 59). Please check the docs at https://home-assistant.io/components/automation/
2019-07-22 21:29:40 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140215442470392] Received invalid command: shopping_list/items
2019-07-23 07:42:16 WARNING (zeroconf-ServiceBrowser__hap._tcp.local.) [zeroconf] Exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/zeroconf.py", line 2245, in send
    bytes_sent = s.sendto(packet, 0, (addr, port))
OSError: [Errno 22] Invalid argument
2019-07-23 07:42:16 ERROR (MainThread) [homeassistant.components.updater] Could not contact Home Assistant Update to check for updates
2019-07-23 07:42:16 ERROR (MainThread) [metno] https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/1.9/ returned Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Temporary failure in name resolution]
2019-07-23 07:42:16 ERROR (MainThread) [homeassistant.components.met.weather] Retrying in 15 minutes
